spring:
  application:
    name: server-discovery

server:
  port: 8085


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8085/eureka
    instance:
      preferIpAddress: true
